### PR TITLE
Added gitlab to regex exceptions

### PR DESCRIPTION
**Pull request by brendenhoffman**

### CODE REVIEW

**Review by RiedleroD — CHANGES_REQUESTED** [review]
looks good to me, but please create the PR for [`RiedleroD:Darklearning`](https://github.com/RiedleroD/userstyles-riedler/tree/Darklearning). Idk if it's possible to change the target of this PR; open a new one if you must.

edit: in any case, thanks for the contribution!

**Comment by brendenhoffman** [comment]
This is my first pull request and I am a bit confused. Did you mean create a PR for the darkarch branch? Doesnt look like I can change the target, but I see how I can create one for the darkarch branch if that is what you want.

**Comment by RiedleroD** [comment]
I suggest you close this PR, copy your addition to the Darklearning branch in your local repo, commit, push, and PR it to my Darklearning branch.

You can also try rebasing and/or cherry-picking, but that requires advanced knowledge of git.

**Comment by brendenhoffman** [comment]
Created new request #15

**Pull request closed without merging**
